### ISSUE TITLE
Non-blocking (async) support

### ISSUE THREAD

**Issue by dougEfresh** [bgreni/helius-rust-sdk#3]
Hey @bgreni ,

What are you thoughts on supporting async reqwests? 
If you wish to keep blocking support then there's a lot of code duplication. 

I don't mind adding async support myself, but want to know your thoughts on how to do this. 

Thanks

**Comment by bgreni** [comment]
Originally I imagined most people using this would be using it for scripts or cli tools and other performance insensitive applications. So I didn't want to force them into taking on the burden of using async Rust.

If you think it would be valuable to add async support I think we should follow the usual pattern of having distinct "sync" and "async" modules. On the bright side you could skip all the deprecated endpoints.

**Comment by dougEfresh** [comment]
How do we structure this  "async"  module? What does the directory structure look like? 
solana uses a module named "nonblocking" . Should async code be in src/async? 

I just want to emphasize that this is duplicated code. One can try to use #cfg features and maybe fancy macros, but at the end of the day, its duplicated code.

**Comment by bgreni** [comment]
I'm not terribly knowledgable as to how other crates handle maintaining separate blocking/non-blocking modules, but I think having a "src/nonblocking" module would be fine. I don't think it's that high of a priority though considering I already have to get around to getting feature parity with the current Helius spec (priority fee api, txn websockets, compressed nft mint). So unless someone comes around and explicitly asks for it I'd rather not open that can of worms.
